<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Common.props" />
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <OutputType>Library</OutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Description>Generates frontend Vue.js metadata, models, api clients, and view models for Coalesce projects. Learn more at https://coalesce.intellitect.com/stacks/vue/overview.html</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IntelliTect.Coalesce.CodeGeneration.Api\IntelliTect.Coalesce.CodeGeneration.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" />
  </ItemGroup>
</Project>
