<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Common.props" />
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <OutputType>Library</OutputType>
    <Description>Generates ASP.NET Core API controllers, DTOs, and Semantic Kernel plugins for Coalesce projects. Learn more at https://coalesce.intellitect.com/</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\IntelliTect.Coalesce.CodeGeneration\IntelliTect.Coalesce.CodeGeneration.csproj" />
    <ProjectReference
      Include="..\IntelliTect.Coalesce\IntelliTect.Coalesce.csproj" />
  </ItemGroup>
</Project>
